---

- name: Install dconf pre-requisites
  package:
    name: python2-psutil

- block:
    - name: Build out list of dictionary items
      set_fact:
        dconf_expanded_dict: |
          {% set dconf_dict = dict() -%}
            {% for root in gnomeshell_dconf_settings -%}
              {% for key in gnomeshell_dconf_settings[root] -%}
              {% set x=dconf_dict.__setitem__('/'.join([root,key]),gnomeshell_dconf_settings[root][key]) -%}
              {%- endfor %}
          {%- endfor %}
          {{ dconf_dict }}

    - name: Configure DCONF settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_dict: "{{ dconf_expanded_dict }}"
  become_user: "{{ gnomeshell_user }}"
