---

- name: Configure gnome dconf settings
  import_tasks: dconf.yml
  when: gnomeshell_dconf_settings
  tags: dconf

- name: Install gnome-tweak extensions
  import_tasks: extensions.yml
  tags: extensions
