---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: gnomeshell_role_f26
    image: fedora:26
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
